# Module: beat
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/master/metricbeat-module-beat.html

- module: beat
  xpack.enabled: true
  period: 10s
  hosts: ["http://filebeat:5066"]
  #username: "user"
  #password: "secret"
