# Module: logstash
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/master/metricbeat-module-logstash.html

- module: logstash
  xpack.enabled: true
  period: 10s
  hosts: ["logstash:9600"]
  #username: "user"
  #password: "secret"